### ISSUE TITLE
OSSN Student Summit (2018) 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/OSSN#112]
### What do we need to decide
- [X] Who we're going to invite ( 9 existing clubs (18), 4-5 new clubs (10))
- [ ] Location (*Drexel? or Portland -  @bacharakis to confirm)
- [ ] Date l*Aug 3-5, Aug 10-12]

### What do we need to do 
- [ ] Invite students to register
       - Create the form @LucyeoH                        
       - Create the email (existing clubs + new clubs) @LucyeoH                        
- [ ] Arrange [agenda](https://docs.google.com/document/d/1c2QtFxdP5Df0-BTWqR4mFqpgXWu8Emq5aleg0YDutGY/edit)
- [ ] Invite Speakers
- [ ] Finalize attendees

Students/speakers/staff - 
- [ ] Book accommodations
- [ ] Book meals
- [ ] Book a fun event 
- [ ] Book flights (students & speakers)

- [ ] Sign the CPG & form about expenses
- [ ] Finalize agenda 
- [ ] Pre meet-up training/connecting/work

### Links/resources
any relevant links/resources
