### ISSUE TITLE
We maintain a network of healthy clubs reflected by Club Captain's reporting an NPS

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/OSSN#126]
We maintain a network of healthy clubs reflected by Club Captain's reporting an NPS of 35% or higher.

### What this includes
- [ ] Monthly Newsletters (@lucyeoh) 
- [ ] Monthly calls (@bacharakis )
- [ ] Onboarding Club Captains  (@bacharakis )
- [ ] 1:1 meetings with Captains  (@bacharakis )
- [ ] Summer Summit (@lucyeoh) 
- [ ] Access to speakers ?
