### ISSUE TITLE
Sexy, Quick OSSN Explanation

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/OSSN#54]
Clearly define the value exchange. 
Turn it into an easy way to talk about and share this value exchange. 

- [ ] What are the benefits people get from being part of this network - Brainstorm. 
- [ ] What are the problem's we're solving. 
- [ ] Pull out compelling key words and start making that a compelling statement (initial copy)
