### ISSUE TITLE
Pre Experiments Survey

### ISSUE THREAD

**Issue by bacharakis** [mozilla/OSSN#66]
Design, build and release a survey for gathering information around the experience of people while trying to contribute to Open Source projects.
The results of this survey will help us identify in which step of the journey students drop most and prioritize our experiments accordingly.

### Tasks ###
- [x] Draft the survey questions [link](https://docs.google.com/document/d/1df-tD2YDSwvnQMY55DjtV2LDEn2zpqLhcITdixYK7u4/edit)
- [x] Review the survey questions (@flekkowich, Ilana, Matt)
- [x] Build the survey in [surveygizmo](https://www.surveygizmo.com/s3/4160758/OSSN-Contribute-to-Open-Source) (@bacharakis) 
- [x] Build outreach strategy (@bacharakis) - [link](https://docs.google.com/spreadsheets/d/1rv3W0T16PmBEL_lS3lDpzL-MKUAe5-Y2Gkcb_un78vE/edit#gid=0)
- [x] Publish the survey (@bacharakis)
- [x] Confirm gender questions (@emmairwin)

 ### Links / resources ###
- [Survey questions](https://docs.google.com/document/d/1df-tD2YDSwvnQMY55DjtV2LDEn2zpqLhcITdixYK7u4/edit
- SurveyGizmo link](https://www.surveygizmo.com/s3/4160758/OSSN-Contribute-to-Open-Source)

**Comment by bacharakis** [comment]
On Thursday I had an amazing call with Matt (our researcher) who provided a lot and useful insights on the questions and the structure of the survey.

Today I incorporated his feedback intro Surveygizmo and I would like your review and thoughts @flekkowich .

Thank you
-Christos

**Comment by bacharakis** [comment]
The survey is finalized and sent to the 60 students who signed up for the experiments.

**Comment by bacharakis** [comment]
I just attached the outreach strategy for our survey.
